Prevent multiprocessing children to fork
NewbiZ/s3pd pull request #6
Opened 2018-12-11 21:38 UTC by omar-masmoudi

2018-12-12 03:11 UTC, NewbiZ requested changes

2018-12-12 03:11 UTC, NewbiZ commented on s3pd/__init__.py
> +    # Prevent multiprocessing children to fork
This seems to be an indirect way of checking if the current process is a daemon or not. Why not just use:
```python
from multiprocessing import Pool, current_process

# [...]

if current_process().daemon == True:
    processes = 1
```

2018-12-12 03:22 UTC, NewbiZ commented
Can you add the message "Fixes issue #4" in your next commit? :)

2018-12-12 08:25 UTC, omar-masmoudi commented on s3pd/__init__.py
> +    # Prevent multiprocessing children to fork
Fine with me, will amend and test again.
I did it on purpose to prevent not-daemonize children to fork based on latest remarks, but I see Philippe agrees with the comment so I'll proceed.

2018-12-13 08:38 UTC, NewbiZ approved these changes

2018-12-13 08:38 UTC, merged